services:
  - type: web
    name: preschool-me
    env: node
    plan: starter
    branch: main
    buildCommand: npm install && npm run db:setup && npm run build
    startCommand: npm run start
    root: .
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://preschool-me.onrender.com
      - key: NEXTAUTH_SECRET
        value: "f9e8d7c6b5a43210f9e8d7c6b5a43210f9e8d7c6b5a43210"
      - key: DATABASE_URL
        value: "postgresql://preschool_me_db_user:XrXu63afns7DdEidBbNh1j7VDOrEfD3D@dpg-d81mildckfvc739vo890-a/preschool_me_db"

databases:
  - name: preschool-me-db
    plan: starter
    region: oregon
    databaseName: preschool_me
    engine: postgres
